stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/WineQT.csv
    outs:
    - data/raw/WineQT.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/WineQT.csv
    outs:
    - data/processed/train_WineQT.csv
    - data/processed/test_WineQT.csv

  train_evaluate:
    cmd: python src/train_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_WineQT.csv
    - data/processed/test_WineQT.csv
    - src/train_evaluate.py
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/model.joblib